---
# .gitlab-ci.yml

spec:
  inputs:
    cookies:
      type: string
      description: After authenticating (via CAC) with MCSC's SPEAR system, copy your cookies and paste them here.
      default: None

---
stages:
  - deliver

adoc-tickets:
  stage: deliver
  image: registry.cdso.army.mil/cdso/containers/approved-base/python_alpine:3.11
  timeout: 3h
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - when: never
  before_script:
    - |
      echo "machine code.cdso.army.mil
      login gitlab-ci-token
      password ${CI_JOB_TOKEN}" > ~/.netrc
    - pip install -r requirements.txt
  variables:
    CURL_CA_BUNDLE: /usr/local/share/ca-certificates/dod.crt
    PYTHONUNBUFFERED: "1"
    RUNNER_SCRIPT_TIMEOUT: 2h50m
    RUNNER_AFTER_SCRIPT_TIMEOUT: 5m
    SPEAR_COOKIES_REQUEST_HEADER: $[[ inputs.cookies ]]
  script:
    - python -u main.py

